language: node_js
node_js:
  - "0.10"
  - "4.9"
  - "6.14"
  - "8.11"
  - "10.8"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Skip updating shrinkwrap / lock
  - "npm config set shrinkwrap false"
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script:
  # Run test script
  - "npm run-script test-ci"
  # Run linting
  - "npm run-script lint"
after_script:
  # Report coverage
  - "test -d .nyc_output && npm install coveralls@2 && nyc report --reporter=text-lcov | coveralls"
