language: node_js
node_js:
  - "0.10"
  - "4.9"
  - "6.14"
  - "8.11"
  - "10.8"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Configure npm
  - |
    # Skip updating shrinkwrap / lock
    npm config set shrinkwrap false
  # Update Node.js modules
  - |
    # Prune & rebuild node_modules
    if [[ -d node_modules ]]; then
      npm prune
      npm rebuild
    fi

script:
  - |
    # Run test script
    npm run-script test-ci
  - |
    # Run linting
    npm run-script lint
after_script:
  - |
    # Upload coverage to coveralls, if exists
    if [[ -d .nyc_output ]]; then
      npm install --save-dev coveralls@2
      nyc report --reporter=text-lcov | coveralls
    fi
