language: node_js
node_js:
  - "0.10"
  - "4.8"
  - "6.11"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
